version: '3.9'

services:
  caddy-gen:
    container_name: caddy-gen
    image: wemakeservices/caddy-gen:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - caddy-certificates:/data/caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - bot

  bot:
    build: .
    container_name: tg-dl-bot
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "virtual.host=mydomain.com" # Replace mydomain.com with your domain
      - "virtual.port=8081"
      - "virtual.tls-email=hello@mydomain.com" # Set your email here to enable SSL

volumes:
  caddy-certificates:
